---
title: "Graphs Joinpoint"
author: "Luis E Segura"
date: `r Sys.Date()` 
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
options(tinytex.verbose = TRUE)

packages <- c( "readxl","tidyverse","ggthemes","ggrepel", "here")

for (package in packages) {
  library(package, character.only=T)
}


data <- read_excel("C:/Users/les2196/Dropbox/PGIF 2020/Graphs/data points - joinpoint graphs.xlsx", sheet = 1)
regions <- read_excel("C:/Users/les2196/Dropbox/PGIF 2020/Graphs/data points - joinpoint graphs.xlsx", sheet = 3)


```


```{r data wrangling, }
data <- data %>%
  select(!ends_with(c("Mexico", " USA", "4", "10"))) %>%
  pivot_longer(cols = starts_with("Observed"), 
               names_to = "region", 
               values_to = "observed") %>% 
  rename(modeled = `Modeled Brazil`, 
         joinpoint = `Joinpoint location...7`, 
         year = Year) %>%
  mutate(region = 1) %>%
  relocate(c(region, observed), .before = modeled)

data <- regions %>% 
  filter(!is.na(Year)) %>%
  select(Year, `Observed...5`, `Modeled...6`, `Joinpoint location...7`) %>%
  rename(`observed Norte` = `Observed...5`) %>%
  pivot_longer(cols = starts_with("observed"), 
               names_to = "region", 
               values_to = "observed") %>%
  rename(modeled = `Modeled...6`, 
         joinpoint = `Joinpoint location...7`, 
         year = Year) %>%
  mutate(region = 2, 
         observed = as.numeric(observed)) %>%
  relocate(c(region, observed), .before = modeled) %>%
  bind_rows(., data) 


data <- regions %>% 
  filter(!is.na(Year)) %>%
  select(Year, `Observed...8`, `Modeled...9`, `Joinpoint location...10`) %>%
  rename(`observed Nordeste` = `Observed...8`) %>%
  pivot_longer(cols = starts_with("observed"), 
               names_to = "region", 
               values_to = "observed") %>%
  rename(modeled = `Modeled...9`, 
         joinpoint = `Joinpoint location...10`, 
         year = Year) %>%
  mutate(region = 3, 
         observed = as.numeric(observed)) %>%
  relocate(c(region, observed), .before = modeled) %>%
  bind_rows(., data) 

data <- regions %>% 
  filter(!is.na(Year)) %>%
  select(Year, `Observed...11`, `Modeled...12`, `Joinpoint location...13`) %>%
  rename(`observed Centro-Oeste` = `Observed...11`) %>%
  pivot_longer(cols = starts_with("observed"), 
               names_to = "region", 
               values_to = "observed") %>%
  rename(modeled = `Modeled...12`, 
         joinpoint = `Joinpoint location...13`, 
         year = Year) %>%
  mutate(region = 4, 
         observed = as.numeric(observed)) %>%
  relocate(c(region, observed), .before = modeled) %>%
  bind_rows(., data) 

data <- regions %>% 
  filter(!is.na(Year)) %>%
  select(Year, `Observed...14`, `Modeled...15`, `Joinpoint location...16`) %>%
  rename(`observed Sudeste` = `Observed...14`) %>%
  pivot_longer(cols = starts_with("observed"), 
               names_to = "region", 
               values_to = "observed") %>%
  rename(modeled = `Modeled...15`, 
         joinpoint = `Joinpoint location...16`, 
         year = Year) %>%
  mutate(region = 5, 
         observed = as.numeric(observed)) %>%
  relocate(c(region, observed), .before = modeled) %>%
  bind_rows(., data) 

data <- regions %>% 
  filter(!is.na(Year)) %>%
  select(Year, `Observed...17`, `Modeled...18`, `Joinpoint location...19`) %>%
  rename(`observed Sul` = `Observed...17`) %>%
  pivot_longer(cols = starts_with("observed"), 
               names_to = "region", 
               values_to = "observed") %>%
  rename(modeled = `Modeled...18`, 
         joinpoint = `Joinpoint location...19`, 
         year = Year) %>%
  mutate(region = 6, 
         observed = as.numeric(observed)) %>%
  relocate(c(region, observed), .before = modeled) %>%
  bind_rows(., data)


data <- data %>%
  mutate(filter = ifelse(year %in% c(2000, 2018), 1,
                         ifelse(!is.na(joinpoint), 1, 0)), 
         region = factor(region, labels = c("All Brazil", "North", 
                                            "Northeast", "Midwest", 
                                            "Southeast", "South"))) %>%
  filter(filter == 1) %>%
  select(!filter)
  
mylist <- list()


for(i in unique(data$region)){
  if(i == "All Brazil"){
    a <- data %>% filter(region == i)
    a <- as.data.frame(with(a, cbind(embed(modeled, 2), embed(year, 2))))
    colnames(a) <- c('yend','y','xend','x')
    a$col <- ifelse(a$x == 2000, 1, 
                    ifelse(a$x == 2012, 3, 2))
    a$region <- i
    mylist[[i]] <- a
    
  } 
  
  else if(i == "North"){
    b <- data %>% filter(region == i)
    b <- as.data.frame(with(b, cbind(embed(modeled, 2), embed(year, 2))))
    colnames(b) <- c('yend','y','xend','x')
    b$col <- ifelse(b$x == 2000, 1,
                      ifelse(b$x == 2013, 3, 
                             ifelse(b$x == 2016, 4, 2)))
    b$region <- i
    mylist[[i]] <- b
    
  } 
  
  else if(i == "Northeast"){
    c <- data %>% filter(region == i)
    c <- as.data.frame(with(c, cbind(embed(modeled, 2), embed(year, 2))))
    colnames(c) <- c('yend','y','xend','x')
    c$col <- ifelse(c$x == 2000, 1, 2)
    c$region <- i
    mylist[[i]] <- c
    
  } 
  
  else if(i == "Midwest"){
    d <- data %>% filter(region == i)
    d <- as.data.frame(with(d, cbind(embed(modeled, 2), embed(year, 2))))
    colnames(d) <- c('yend','y','xend','x')
    d$col <- ifelse(d$x == 2000, 1, 2)
    d$region <- i
    mylist[[i]] <- d
  }
  
  else if(i == "Southeast"){
    e <- data %>% filter(region == i)
    e <- as.data.frame(with(e, cbind(embed(modeled, 2), embed(year, 2))))
    colnames(e) <- c('yend','y','xend','x')
    e$col <- ifelse(e$x == 2000, 1, 
                    ifelse(e$x == 2012, 3, 2))
    e$region <- i
    mylist[[i]] <- e
  }
  
  else if(i == "South"){
    f <- data %>% filter(region == i)
    f <- as.data.frame(with(f, cbind(embed(modeled, 2), embed(year, 2))))
    colnames(f) <- c('yend','y','xend','x')
    f$col <- ifelse(f$x == 2000, 1, 2)
    f$region <- i
    mylist[[i]] <- f
  }
}

data.plot <- bind_rows(mylist)

```

```{r plot, }

data %>%
  ggplot(aes(x = year, y = observed, group = region)) +
  geom_point(colour = "darkred", shape = 15) + 
  geom_segment(data = data.plot, 
               aes(x = x, y = y, xend = xend, yend = yend, 
                   colour = factor(col), linetype = region), 
                show.legend = F, linewidth = 1) + 
   labs(x = "Year", y = "Overdose Death Rates per 100,000") + 
  geom_label_repel(data = data %>% filter(year == 2018), 
                   aes(label = region), box.padding = 0.35, point.padding = 0.5, 
                   max.overlaps = 50, nudge_x = 0.6) +
  # geom_label(data = data %>%
  #              filter(year == 2018), aes(label = region), nudge_y = 0, nudge_x = 0.5) + 
  scale_x_continuous(breaks = seq(2000, 2018, by = 1)) + 
  scale_y_continuous(breaks = seq(0.14, 1.34, by = 0.10)) +
  scale_color_manual(values = c("blue", "darkgreen", "brown2", "purple")) +
  expand_limits(y = c(0.14, 1.24))  + 
  theme(legend.position = "none") + 
  theme_bw() 

setwd("C:/Users/les2196/Dropbox/PGIF 2020/Graphs/")

ggsave("brazil_graph.jpeg", width = 18 ,height = 8, units = "in", dpi = 1200)  

```

