---
title: "Enrollment Report"
author: "Luis E Segura"
date: "2023-01-05"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

options(tinytex.verbose = TRUE)

rm(list = ls())

library(tidyverse)

```

```{r, load datasets }
setwd("/Volumes/Luis/Datasets/NSDUH datasets/rdata/")

load("NSDUH_2020.RData")

my_files <- list.files(pattern = "*.RData", full.names = T) 

my_files <- my_files[-1]

for(i in my_files){
  load(i)
}

ls(pattern = "PUF")

dataList <- list(NSDUH13 = PUF2013_090718, 
                 NSDUH14 = PUF2014_090718,
                 NSDUH15 = PUF2015_021518, 
                 NSDUH16 = PUF2016_022818, 
                 NSDUH17 = PUF2017_100918, 
                 NSDUH18 = PUF2018_100819, 
                 NSDUH19 = PUF2019_100920, 
                 NSDUH20 = NSDUH_2020) 


dataList <- lapply(dataList, function(x){names(x) <- tolower(names(x));return(x)})


for(i in 1:8){
  if("poverty2" %in% colnames(dataList[[i]]) == T){
    dataList[[i]] <- dataList[[i]] %>% 
      rename(., "poverty" = "poverty2")
  } 
  if("poverty3" %in% colnames(dataList[[i]]) == T){
    dataList[[i]] <- dataList[[i]] %>% 
      rename(., "poverty" = "poverty3")
  }
}

myvars <- c("questid2", "vestr", "verep", "analwt_c", "newrace2", 
            "irsex",  "catag6", "poverty", "irki17_2", 
            "income")

find_names <- function(x, j) {
  print(grep(x, names(dataList[[j]]), value = T))
}

for(i in 1:8){ 
  find_names("vestr", i)
}

dataList[[8]] <- dataList[[8]] %>% 
  rename("vestr" = "vestrq1q4_c", 
         "analwt_c" = "analwtq1q4_c", )



for(i in 1:8){
  dataList[[i]] <- dataList[[i]][ , myvars] ### subsetting each dataset with only the variables in myvars
  dataList[[i]][["year"]] <- i + 2012 ### creating a year variable (starting year - 1)
  dataList[[i]][["newid"]] <- seq_len(nrow(dataList[[i]])) ### creating a numeric variable 1 to the length of the dataset.
  dataList[[i]][["realid"]] <- (dataList[[i]][["year"]] * 1e5) + as.numeric(dataList[[i]][["newid"]]) ### creating a unique id for each observation
}

  
nsduh <- do.call(rbind, dataList) ### unlist the datasets and append them together


rm("PUF2014_090718", "PUF2015_021518", "PUF2016_022818", 
   "PUF2017_100918", "PUF2018_100819", "PUF2019_100920", 
   "NSDUH_2020", "dataList", "PUF2013_090718") ### remove extra stuff from the environment
nsduh

```

```{r, }
nsduh <- nsduh %>%
  mutate(race = factor(newrace2, labels = c("NH whites", "NH Blacks", 
                                           "NH Native Am/AK Native", "Native HI/Other Pac Isl", 
                                           "NH Asian", "NH More than one race", "Hispanics")), 
         sex = factor(irsex, labels = c("Male", "Female")))

nsduh %>%
  filter(sex == "Female" & catag6 > 1 & irki17_2 > 1) %>%
  group_by(race) %>%
  count() 
  
```

```{r, parenting women}
nsduh %>%
  mutate(parenting = ifelse(irki17_2 > 1, 1, 0)) %>%
  filter(sex == "Female") %>%
  group_by(parenting) %>%
  summarise(n = n()) %>%
  mutate(freq = (n / sum(n)) * 100)

nsduh %>%
  filter(sex == "Female" & catag6 > 1 & irki17_2 > 1) %>%
  group_by(race) %>%
  summarise(n = n()) %>%
  mutate(freq = (n / sum(n)) * 100)

nsduh %>%
  filter(sex == "Female" & catag6 > 1 & irki17_2 > 1) %>%
  group_by(year) %>%
  summarise(n = n()) %>%
  mutate(freq = (n / sum(n)) * 100) %>%
  mutate(total = mean(n))

library(survey)
library(srvyr)

nsduh.design <- nsduh %>% 
  as_survey_design(strata = vestr, 
                   ids = verep, 
                   weights = analwt_c, 
                   nest = T)

nsduh.design %>% 
  filter(sex == "Female" & catag6 > 1 & irki17_2 > 1) %>%
  group_by(race) %>%
  summarise(prop = survey_prop() * 100)

```
